version: '3'
services:
    web:
        image: 'jupyter_note'
        ports: 
            - '8888:8888'
        volumes:
            - ~/BDP2_review/work:/home/jovyan/work         
        environment: 
            - GEN_CERT=yes
    portainer:
        image: 'portainer/portainer'
        ports:
            - '9000:9000'
        restart: always      
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/portainer_data:/data
